### PR TITLE
New Icon created and added

### PR DESCRIPTION
**Pull request by sonu7089**
-> Created a new icon for the extension
-> Made the relevant changes
-> Provided a light version of the logo to make the extension compact if required.

### CODE REVIEW

**Comment by AnkushSinghGandhi** [comment]
This symbol is a little too bright, and I'd like something close to the old one.

**Comment by sonu7089** [comment]
image
Will this work ?

**Comment by AnkushSinghGandhi** [comment]
I am lokin for something simple like this

**Comment by AnkushSinghGandhi** [comment]
Connect with me on discord or Twitter I'll guide you.

**Pull request closed without merging**
